#!/bin/sh /etc/rc.common

. /usr/share/libubox/jshn.sh

START=95
USE_PROCD=1
NAME=nbtverify
PROG=/usr/bin/nbtverify
RUNTIME_DIR=/var/run/nbtverify
CACHE_FILE=$RUNTIME_DIR/url.txt
STATUS_FILE=$RUNTIME_DIR/status.json

write_config() {
	local path="$1"
	local username="$2"
	local password="$3"
	local mobile="$4"
	local ping="$5"

	json_init
	json_add_string username "$username"
	json_add_string password "$password"
	json_add_boolean mobile "$mobile"
	json_add_string cache "$CACHE_FILE"
	json_add_string status "$STATUS_FILE"
	json_add_string ping_url "$ping"
	json_dump > "$path"
	chmod 0600 "$path"
}

start_instance() {
	local section="$1"
	local enabled username password mobile ping config_file

	config_get_bool enabled "$section" enabled 0
	[ "$enabled" -eq 1 ] || return 0

	config_get username "$section" username
	config_get password "$section" password
	config_get_bool mobile "$section" mobile 1
	config_get ping "$section" ping "http://10.80.92.85/"

	if [ -z "$username" ] || [ -z "$password" ]; then
		logger -t nbtverify "not starting: username or password is empty"
		return 1
	fi

	umask 077
	mkdir -p "$RUNTIME_DIR"
	chmod 0700 "$RUNTIME_DIR"
	touch "$CACHE_FILE" "$STATUS_FILE"
	chmod 0600 "$CACHE_FILE" "$STATUS_FILE"
	: > "$STATUS_FILE"

	config_file="$RUNTIME_DIR/$section.json"
	write_config "$config_file" "$username" "$password" "$mobile" "$ping"

	procd_open_instance "$section"
	procd_set_param command "$PROG" -c "$config_file" service
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_load 'nbtverify'
	config_foreach start_instance 'server'
}

service_triggers() {
	procd_add_reload_trigger "nbtverify"
}
