name: publish

on:
  push:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build
        run: 
          dotnet fsi ./tools/pack.fsx -v ${{ github.ref_name }}
        
      # upload artifacts
      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          path: dist/*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          
